# Generated by Django 3.2.5 on 2024-06-21 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_generator', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20)),
                ('qr_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_generator.qrcode')),
            ],
        ),
    ]
